### ISSUE TITLE
Generate schedule using the free time array and pending tasks, and update the student record in mlab with that generated schedule

### ISSUE THREAD

**Issue by rohitnaik246** [neelkapadia/WolfPlanner#14]
After scheduling.py is in proper format, write the scheduling code.
If free time entry not present for the user, call the free time function, else generate schedule.
After generating, add the schedule to the student record in mlab.

**Comment by neelkapadia** [comment]
Check the latest commit. Have added scheduling algorithm. Still needs touch-ups though.

**Comment by rohitnaik246** [comment]
Awesome! I'll take care of that. Don't worry!

**Comment by rohitnaik246** [comment]
Added to the student_record entry in mlab!
