### ISSUE TITLE
Write code for fetching and parsing user input from chatbot into mlab DB & Display generated schedule to the user

### ISSUE THREAD

**Issue by neelkapadia** [neelkapadia/WolfPlanner#6]
high time we set the flow of the system

**Comment by rohitnaik246** [comment]
Details about this - 
1. Fetch the input (classes, tasks for the week) either by creating an HTML form within the chatbot or opening a link to a form for input or asking the details as an interaction between the user and chatbot. 
2. Get that input parsed in the required format (data types, lists, dicts, etc.) and insert code written from js to mlab (mongo)

@RohanChandavarkar can you please get this done by Saturday?
